dist: jammy
sudo: required
language: java
os: linux
arch: s390x
jdk: openjdk17
cache:
  directories:
  - "$HOME/.m2"
addons:
  hosts:
  - kafka
  - keycloak
  - hydra
  - hydra-jwt
  - mockoauth
  - kerberos
  apt:
    packages:
      - maven
before_install:
  - sudo apt install curl -y
  - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
  - sudo apt-get install nodejs -y
  - sudo npm install -g pnpm
env:
  global:
  - NODE_OPTIONS="--dns-result-order=ipv4first"
  - PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - TAG=${TRAVIS_TAG:-latest}
  - BRANCH=${TRAVIS_BRANCH:-main}
script:
- "./.travis/build-s390x.sh"
