dist: jammy
sudo: required
language: java
os: linux
arch: s390x
jdk: openjdk17
cache:
  directories:
  - "$HOME/.m2"
jobs:
  include:
    - os: linux
      arch: s390x
      jdk: openjdk17
      addons:
        hosts:
          - kafka
          - keycloak
          - hydra
          - hydra-jwt
          - mockoauth
          - kerberos
        apt:
          packages:
            - maven
      env:
        - DOCKER_COMPOSE_VERSION=v2.24.5
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
        - update-java-alternatives --list
        - java -version
        - javac -version
        - echo JAVA_HOME: $JAVA_HOME
        - sudo apt -y remove openjdk11
        - mvn -version
env:
  global:
  - PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - TAG=${TRAVIS_TAG:-latest}
  - BRANCH=${TRAVIS_BRANCH:-main}
script:
- "./.travis/build-s390x.sh"
