version: '3.5'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: keycloak
    ports:
      -  8080:8080
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_HOSTNAME: "keycloak"
      KC_HTTP_ENABLED: "true"
    command: "start --auto-build --features=token-exchange,authorization,scripts"
