apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
  selector:
    app: keycloak
  type: NodePort

---

apiVersion: v1
kind: Pod 
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  containers:
  - name: keycloak
    image: quay.io/keycloak/keycloak:23.0.5
    args: ["-v", "start", "--import-realm", "--features=token-exchange,authorization,scripts"]
    env:
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: admin
    - name: KC_HOSTNAME
      value: keycloak
    - name: KC_HTTP_ENABLED
      value: "true"
    ports:
    - name: http
      containerPort: 8080
    - name: https
      containerPort: 8443
    readinessProbe:
      httpGet:
        path: /realms/master
        port: 8080
    volumeMounts:
      - name: realms
        mountPath: /opt/keycloak/data/import
  volumes:
    - name: realms
      configMap:
        name: realms
